### ISSUE TITLE
stegoVeritas broken

### ISSUE THREAD

**Issue by kevinelliott** [DominicBreuker/stego-toolkit#11]
With latest docker image:

```
##################################
########## stegoVeritas ##########
##################################
/opt/scripts/check_jpg.sh: line 113: stegoveritas.py: command not found
```

**Comment by myrdyr** [comment]
Seems like a lot has changed in the stegoVeritas repository. The fix is to run this: `cd /opt/stegoVeritas/ && python3 setup.py install && stegoveritas_install_deps` and from then on just call `stegoveritas` instead of `stegoveritas.py`.

Maybe the author can update the script when he discovers this.

**Comment by DominicBreuker** [comment]
true :/ no way around building some test script to check all tools after install. hope to find time for it
